name: suho
description: "Application for You."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  envied: ^0.5.4+1

  http: ^1.2.2
  just_audio: ^0.9.33
  dart_openai: ^5.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    #환경 요소
    - assets/config/.env

    #Suho 로고